openapi: 3.0.3
info:
  title: Скрипт для преобразования Excel конкретного типа в XML согласно заданному шаблону
  description: Excel содержит 2 столбца без заголовков (1-ый с содержанием sku, 2-ой содержит количество).<br>
    Xml формируется с соответствии с заранее присланным шаблоном
  version: 1.0.0
servers:
  - url: 'example.com'
paths:
  /index.php:
    post:
      summary: Данные для формирования xml
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              minProperties: 2
              required:
                - date
              properties:
                date:
                  type: string
                  description: Дата запланированной отгрузки в формате YYYY-MM-DD
                  example: 2022-03-18
                spbFile:
                  type: string
                  description: Таблица Excel (расширение xls или xlsx) для склада Питера содержит 2 столбца без заголовков <br>
                    (1-ый с содержанием sku, 2-ой содержит количество). Хотя бы 1 таблица должна присутствовать
                  format: binary
                mskFile:
                  type: string
                  description: Таблица Excel (расширение xls или xlsx) для склада Москвы содержит 2 столбца без заголовков <br>
                    (1-ый с содержанием sku, 2-ой содержит количество). Хотя бы 1 таблица должна присутствовать
                  format: binary
      responses:
        200:
          description: OK
        400:
          description: Ошибка присланных данных. Либо нет даты, либо не прислано ни одной таблицы соответсвующего расширения